# Macro file to aid visualisation when running in interactive mode

# open graphical driver we want
/vis/open TSG 

# draw the volume
/vis/drawVolume

# tell geant to record particle paths 
/tracking/storeTrajectory 1

# tell geant to accumulate these trajectories rather than wiping after each event
# can specify the number of events to store before capping
# (to avoid overloading ram on bigger stat runs)
/vis/scene/endOfEventAction accumulate 100

# then run with number of particles
/run/beamOn 1000

# now add back the trajectories accumulated earlier
/vis/scene/add/trajectories smooth

# specify the colour of the trajectories based on particle type
/vis/modeling/trajectories/create/drawByParticleID myParticleColours
/vis/modeling/trajectories/myParticleColours/set gamma green
/vis/modeling/trajectories/myParticleColours/set neutron blue

# force viewer to only draw the events kept in local memory
/vis/viewer/rebuild

