# Macro file to test the simulation works

# specify number of threads
/run/numberOfThreads 1

# Initialise geant kernel
/run/initialize

# specify output directory (overwrite this in the .sh script)
/output/dir /rds/projects/b/bishopjw-dli-neutron/John/Geant/AmBe/outputs/2026_05_19__20_28_36

# neutron with set energy
/gun/particle neutron
/gun/energy 5 MeV

# Fire specified number of neutrons from particleGun
/run/beamOn 10