/// \file AmBe/src/PrimaryGeneratorAction.cc
/// \brief Implementation of the AmBeStack::PrimaryGeneratorAction class

#include "PrimaryGeneratorAction.hh"

#include "G4Box.hh"
#include "G4LogicalVolume.hh"
#include "G4LogicalVolumeStore.hh"
#include "G4ParticleGun.hh"
#include "G4ParticleTable.hh"
#include "G4SystemOfUnits.hh"
#include "Randomize.hh"
#include "globals.hh"

namespace AmBeStack
{

// constructor to set up source particle generation (i.e. AmBe source spectra)
// class::function/constructor 
// defining the code for the constructor that was 
// initialised in the header file
// like defining class functions in python with class.function
PrimaryGeneratorAction::PrimaryGeneratorAction()
    // : starts "member intialiser list"
    // zone which runs before the code inside {} 
    : G4VUserPrimaryGeneratorAction(), // - parent setup (run the basics __init__ of the native geant class first)
    fParticleGun(nullptr) // - assign member variable (defined in .hh) first value 
    // may aswell start with fParticleGun = None (equiv. syntax in python)
{
    G4int n_particle = 1; // number of particles to generate per event
    // initialise particle gun
    // notice "new"
    // makes the object "on the heap" (large memory pool)
    // means permanent  - lives until manually deleted
    // (see destructor definition below)
    fParticleGun = new G4ParticleGun(n_particle); 

    // monoenergetic neutron source for now
    // will change to sample from true AmBe spectrum later 
    // particle table instance
    // notice no "new" here
    // makes object "on the stack" only exists inside scope {}
    G4ParticleTable* particleTable = G4ParticleTable::GetParticleTable();
    // we want to grab neutron
    G4String particleName = "neutron";
    // particle instance defined by neutron in table
    G4ParticleDefinition* particle = particleTable->FindParticle(particleName);

    // assign this to our particle gun
    fParticleGun->SetParticleDefinition(particle);
    fParticleGun->SetParticleMomentumDirection(G4ThreeVector(0., 0., 1.)); // in z direction for now
    fParticleGun->SetParticleEnergy(10 *MeV); // set energy

}

// destructor to clean up particle gun when simulation has ran
// class::function/destructor here
PrimaryGeneratorAction::~PrimaryGeneratorAction()
{
    delete fParticleGun; 
}

// function to be called at the start of each event
// this is used to place the particles generated by the gun 
// into the volume of interest
// class::
void PrimaryGeneratorAction::GeneratePrimaries(G4Event* event)
{
    // !!!!!!!!!!!!! for debugging !!!!!!!!!!
    G4cout << "Coming from GeneratePrimaries" << G4endl;

    // for now, place them all at origin
    // will change this later so generated isotropically 
    // within AmBe source volume
    G4double x0 = 0.0 *cm;
    G4double y0 = 0.0 *cm;
    G4double z0 = 0.0 *cm;

    // tell particle gun object
    fParticleGun->SetParticlePosition(G4ThreeVector(x0, y0, z0));

    // tell particle gun to generate these particles
    // "PULL TRIGGER"
    fParticleGun->GeneratePrimaryVertex(event);

}

}